# SPDX-FileCopyrightText: 2025 Roland Knall <rknall@gmail.com>
# SPDX-License-Identifier: GPL-2.0-only
"""Email template service for CRUD and rendering operations."""
import re
from decimal import Decimal

from sqlalchemy import and_, or_
from sqlalchemy.orm import Session

from src.models import Company, EmailTemplate, Event, Expense, User
from src.schemas.email_template import (
    EmailTemplateCreate,
    EmailTemplateUpdate,
    TemplateReason,
    TemplateVariableInfo,
)

# Define available template reasons with their variables
TEMPLATE_REASONS = {
    "expense_report": TemplateReason(
        reason="expense_report",
        description="Email template for sending expense reports",
        variables=[
            TemplateVariableInfo(
                variable="{{event.name}}",
                description="Event name",
                example="SPS 2025",
            ),
            TemplateVariableInfo(
                variable="{{event.start_date}}",
                description="Event start date (formatted)",
                example="25.11.2025",
            ),
            TemplateVariableInfo(
                variable="{{event.end_date}}",
                description="Event end date (formatted)",
                example="27.11.2025",
            ),
            TemplateVariableInfo(
                variable="{{event.description}}",
                description="Event description",
                example="Trade show in Nuremberg",
            ),
            TemplateVariableInfo(
                variable="{{company.name}}",
                description="Company name",
                example="Acme Corp",
            ),
            TemplateVariableInfo(
                variable="{{company.recipient_name}}",
                description="Expense recipient name",
                example="Finance Department",
            ),
            TemplateVariableInfo(
                variable="{{expense.total_amount}}",
                description="Total expense amount formatted with currency",
                example="209.91 EUR",
            ),
            TemplateVariableInfo(
                variable="{{expense.count}}",
                description="Number of expenses",
                example="7",
            ),
            TemplateVariableInfo(
                variable="{{expense.currency}}",
                description="Currency code",
                example="EUR",
            ),
            TemplateVariableInfo(
                variable="{{sender.name}}",
                description="Current user's display name",
                example="Roland",
            ),
            TemplateVariableInfo(
                variable="{{sender.email}}",
                description="Current user's email address",
                example="roland@example.com",
            ),
        ],
    ),
}

# Default template content
DEFAULT_EXPENSE_REPORT_TEMPLATE = {
    "name": "Standard Expense Report",
    "reason": "expense_report",
    "subject": "Expense Report: {{event.name}}",
    "body_html": """<p>Dear {{company.recipient_name}},</p>

<p>Please find attached the expense report for:</p>

<ul>
<li><strong>Event:</strong> {{event.name}}</li>
<li><strong>Company:</strong> {{company.name}}</li>
<li><strong>Period:</strong> {{event.start_date}} to {{event.end_date}}</li>
<li><strong>Total:</strong> {{expense.total_amount}} ({{expense.count}} items)</li>
</ul>

<p>This report was generated by {{sender.name}}.</p>

<p>Best regards,<br>
Travel Manager</p>""",
    "body_text": """Dear {{company.recipient_name}},

Please find attached the expense report for:

Event: {{event.name}}
Company: {{company.name}}
Period: {{event.start_date}} to {{event.end_date}}
Total: {{expense.total_amount}} ({{expense.count}} items)

This report was generated by {{sender.name}}.

Best regards,
Travel Manager""",
    "is_default": True,
}


def get_templates(
    db: Session,
    reason: str | None = None,
    company_id: str | None = None,
) -> list[EmailTemplate]:
    """Get all templates, optionally filtered by reason and/or company."""
    query = db.query(EmailTemplate)

    if reason:
        query = query.filter(EmailTemplate.reason == reason)

    if company_id:
        # Get both global templates and company-specific templates
        query = query.filter(
            or_(
                EmailTemplate.company_id.is_(None),
                EmailTemplate.company_id == company_id,
            )
        )

    return query.order_by(EmailTemplate.name).all()


def get_global_templates(db: Session, reason: str | None = None) -> list[EmailTemplate]:
    """Get only global templates (company_id is NULL)."""
    query = db.query(EmailTemplate).filter(EmailTemplate.company_id.is_(None))

    if reason:
        query = query.filter(EmailTemplate.reason == reason)

    return query.order_by(EmailTemplate.name).all()


def get_templates_for_company(
    db: Session,
    company_id: str,
    reason: str,
) -> list[EmailTemplate]:
    """Get templates applicable to a company (company-specific + global)."""
    return (
        db.query(EmailTemplate)
        .filter(
            and_(
                EmailTemplate.reason == reason,
                or_(
                    EmailTemplate.company_id.is_(None),
                    EmailTemplate.company_id == company_id,
                ),
            )
        )
        .order_by(EmailTemplate.company_id.desc(), EmailTemplate.name)  # Company-specific first
        .all()
    )


def get_template(db: Session, template_id: str) -> EmailTemplate | None:
    """Get a template by ID."""
    return db.query(EmailTemplate).filter(EmailTemplate.id == template_id).first()


def get_default_template(
    db: Session,
    company_id: str | None,
    reason: str,
) -> EmailTemplate | None:
    """Get the default template for a reason.

    Priority:
    1. Company-specific default (if company_id provided)
    2. Global default
    """
    if company_id:
        # Try company-specific default first
        company_default = (
            db.query(EmailTemplate)
            .filter(
                and_(
                    EmailTemplate.reason == reason,
                    EmailTemplate.company_id == company_id,
                    EmailTemplate.is_default.is_(True),
                )
            )
            .first()
        )
        if company_default:
            return company_default

    # Fall back to global default
    return (
        db.query(EmailTemplate)
        .filter(
            and_(
                EmailTemplate.reason == reason,
                EmailTemplate.company_id.is_(None),
                EmailTemplate.is_default.is_(True),
            )
        )
        .first()
    )


def create_template(db: Session, data: EmailTemplateCreate) -> EmailTemplate:
    """Create a new email template."""
    # If this is set as default, unset other defaults for the same reason/scope
    if data.is_default:
        _unset_other_defaults(db, data.reason, data.company_id)

    template = EmailTemplate(
        name=data.name,
        reason=data.reason,
        company_id=data.company_id,
        subject=data.subject,
        body_html=data.body_html,
        body_text=data.body_text,
        is_default=data.is_default,
    )
    db.add(template)
    db.commit()
    db.refresh(template)
    return template


def update_template(
    db: Session,
    template: EmailTemplate,
    data: EmailTemplateUpdate,
) -> EmailTemplate:
    """Update an existing email template."""
    # If setting as default, unset other defaults
    if data.is_default is True:
        _unset_other_defaults(db, template.reason, template.company_id, exclude_id=template.id)

    if data.name is not None:
        template.name = data.name
    if data.reason is not None:
        template.reason = data.reason
    if data.subject is not None:
        template.subject = data.subject
    if data.body_html is not None:
        template.body_html = data.body_html
    if data.body_text is not None:
        template.body_text = data.body_text
    if data.is_default is not None:
        template.is_default = data.is_default

    db.commit()
    db.refresh(template)
    return template


def delete_template(db: Session, template: EmailTemplate) -> None:
    """Delete an email template."""
    db.delete(template)
    db.commit()


def count_global_templates(db: Session) -> int:
    """Count the number of global templates."""
    return db.query(EmailTemplate).filter(EmailTemplate.company_id.is_(None)).count()


def is_last_global_template(db: Session, template: EmailTemplate) -> bool:
    """Check if this is the last global template."""
    if template.company_id is not None:
        return False  # Company-specific templates can always be deleted
    return count_global_templates(db) <= 1


def _unset_other_defaults(
    db: Session,
    reason: str,
    company_id: str | None,
    exclude_id: str | None = None,
) -> None:
    """Unset is_default for other templates in the same scope."""
    query = db.query(EmailTemplate).filter(
        and_(
            EmailTemplate.reason == reason,
            EmailTemplate.is_default.is_(True),
        )
    )

    if company_id:
        query = query.filter(EmailTemplate.company_id == company_id)
    else:
        query = query.filter(EmailTemplate.company_id.is_(None))

    if exclude_id:
        query = query.filter(EmailTemplate.id != exclude_id)

    for template in query.all():
        template.is_default = False


def get_reasons() -> list[TemplateReason]:
    """Get all available template reasons with their variables."""
    return list(TEMPLATE_REASONS.values())


def get_reason_variables(reason: str) -> TemplateReason | None:
    """Get variables for a specific reason."""
    return TEMPLATE_REASONS.get(reason)


def get_default_template_content(reason: str) -> dict | None:
    """Get default template content for prefilling new templates."""
    if reason == "expense_report":
        return DEFAULT_EXPENSE_REPORT_TEMPLATE
    return None


def render_template(
    template: EmailTemplate,
    context: dict,
) -> tuple[str, str, str]:
    """Render a template with variable substitution.

    Returns (subject, body_html, body_text).
    """
    subject = _substitute_variables(template.subject, context)
    body_html = _substitute_variables(template.body_html, context)
    body_text = _substitute_variables(template.body_text, context)
    return subject, body_html, body_text


def _substitute_variables(text: str, context: dict) -> str:
    """Substitute {{variable}} placeholders with context values."""
    # Match {{variable.path}} patterns
    pattern = r"\{\{([a-z_]+(?:\.[a-z_]+)*)\}\}"

    def replacer(match: re.Match) -> str:
        path = match.group(1)
        parts = path.split(".")
        value = context
        for part in parts:
            if isinstance(value, dict) and part in value:
                value = value[part]
            else:
                return match.group(0)  # Keep original if not found
        return str(value) if value is not None else ""

    return re.sub(pattern, replacer, text)


def build_expense_report_context(
    event: Event,
    company: Company,
    expenses: list[Expense],
    user: User,
) -> dict:
    """Build context dictionary for expense_report templates."""
    # Calculate totals
    total = sum(e.amount for e in expenses if e.amount) or Decimal("0")

    # Get currency from first expense or default
    currency = expenses[0].currency if expenses else "EUR"

    # Format dates
    date_format = "%d.%m.%Y"
    start_date = event.start_date.strftime(date_format) if event.start_date else ""
    end_date = event.end_date.strftime(date_format) if event.end_date else ""

    return {
        "event": {
            "name": event.name,
            "start_date": start_date,
            "end_date": end_date,
            "description": event.description or "",
        },
        "company": {
            "name": company.name,
            "recipient_name": company.expense_recipient_name or company.name,
        },
        "expense": {
            "total_amount": f"{total:.2f} {currency}",
            "count": str(len(expenses)),
            "currency": currency,
        },
        "sender": {
            "name": user.username,
            "email": user.email or "",
        },
    }


def get_sample_context(reason: str) -> dict:
    """Generate sample context for preview."""
    if reason == "expense_report":
        return {
            "event": {
                "name": "SPS 2025",
                "start_date": "25.11.2025",
                "end_date": "27.11.2025",
                "description": "Trade show in Nuremberg",
            },
            "company": {
                "name": "Acme Corp",
                "recipient_name": "Finance Department",
            },
            "expense": {
                "total_amount": "209.91 EUR",
                "count": "7",
                "currency": "EUR",
            },
            "sender": {
                "name": "Roland",
                "email": "roland@example.com",
            },
        }
    return {}


def ensure_default_template_exists(db: Session) -> EmailTemplate:
    """Ensure a default expense_report template exists. Create if missing.

    This should be called during setup to ensure the system always has
    at least one template.
    """
    existing = get_default_template(db, None, "expense_report")
    if existing:
        return existing

    # Create the default template
    template = EmailTemplate(
        name=DEFAULT_EXPENSE_REPORT_TEMPLATE["name"],
        reason=DEFAULT_EXPENSE_REPORT_TEMPLATE["reason"],
        company_id=None,  # Global template
        subject=DEFAULT_EXPENSE_REPORT_TEMPLATE["subject"],
        body_html=DEFAULT_EXPENSE_REPORT_TEMPLATE["body_html"],
        body_text=DEFAULT_EXPENSE_REPORT_TEMPLATE["body_text"],
        is_default=True,
    )
    db.add(template)
    db.commit()
    db.refresh(template)
    return template
